version: "3"

services:
  eureka-register-center:
    build: ./docker/eureka-register-center
    ports: 
    - "7000:7000"

  manager-zuul:
    build: ./docker/manager-zuul
    ports:
    - "80:80"
    links:
       - eureka-register-center
    depends_on:
      - eureka-register-center
  manager-server-api-admin:
    build: ./docker/manager-server-api-admin
    ports:
      - "11000:11000"
    links:
       - eureka-register-center
    depends_on:
      - eureka-register-center
